# Generated by Django 5.2.5 on 2025-08-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_content_alter_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
    ]
