# Generated by Django 5.2.5 on 2025-08-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
    ]
