# Generated by Django 5.2.5 on 2025-08-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blog_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSSFeed',
        ),
    ]
